env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: nowin
    binary: go-cqhttp
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: 386
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/Mrs4s/go-cqhttp/coolq.Version=v{{.Version}}
  - id: win
    binary: go-cqhttp
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - windows
    goarch:
      - 386
      - amd64
      - arm
    goarm:
      - 7
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/Mrs4s/go-cqhttp/coolq.Version=v{{.Version}}

checksum:
  name_template: "go-cqhttp_checksums.txt"

archives:
  - id: binary
    builds:
      - win
    name_template: "go-cqhttp_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: binary
  - id: nowin
    builds:
      - nowin
      - win
    name_template: "go-cqhttp_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - license: AGPL 3.0
    homepage: https://go-cqhttp.org
    file_name_template: "go-cqhttp_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - deb
      - rpm
    maintainer: Mrs4s

release:
  github:
    owner: j1g5awi
    name: go-cqhttp-nightly
changelog:
  skip: true